name: release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "Version tag for the new release"
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.version }}
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ~1.24
      - name: Build Release
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
